-- Combined Migration: Schema Updates + Row Level Security
-- Date: 2026-01-07
-- Version: 2.4.0
-- Description: Complete database update - schema fields + RLS policies in one migration

-- This migration combines:
-- 1. Schema updates from migration 006 (counters, notifications, etc.)
-- 2. RLS policies from migration 007 (security)

-- =============================================================================
-- PART 1: SCHEMA UPDATES (from migration 006)
-- =============================================================================

-- Add missing fields to USERS table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'total_bookings'
    ) THEN
        ALTER TABLE users ADD COLUMN total_bookings INTEGER DEFAULT 0;
        COMMENT ON COLUMN users.total_bookings IS 'Cached count of total bookings for this user';
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'last_login'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'last_login_at'
    ) THEN
        ALTER TABLE users RENAME COLUMN last_login TO last_login_at;
    END IF;
END $$;

-- Add missing fields to SERVICES table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'services' AND column_name = 'total_bookings'
    ) THEN
        ALTER TABLE services ADD COLUMN total_bookings INTEGER DEFAULT 0;
        COMMENT ON COLUMN services.total_bookings IS 'Cached count of total bookings for this service';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'services' AND column_name = 'total_revenue'
    ) THEN
        ALTER TABLE services ADD COLUMN total_revenue DECIMAL(12, 2) DEFAULT 0;
        COMMENT ON COLUMN services.total_revenue IS 'Cached total revenue generated by this service';
    END IF;
END $$;

-- Add missing fields to BOOKINGS table
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bookings' AND column_name = 'queue_position'
    ) THEN
        ALTER TABLE bookings ADD COLUMN queue_position INTEGER;
        COMMENT ON COLUMN bookings.queue_position IS 'Position in queue for processing';
    END IF;
END $$;

-- Create NOTIFICATIONS table if not exists
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP,
    action_url TEXT,
    action_label VARCHAR(100),
    booking_id UUID REFERENCES bookings(id) ON DELETE CASCADE,
    related_entity_type VARCHAR(50),
    related_entity_id UUID,
    sent_via JSONB DEFAULT '{"app": true, "email": false, "sms": false}'::jsonb,
    priority VARCHAR(20) DEFAULT 'normal',
    expires_at TIMESTAMP,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create ANALYTICS_SNAPSHOTS table if not exists
CREATE TABLE IF NOT EXISTS analytics_snapshots (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    snapshot_date DATE NOT NULL,
    timeframe VARCHAR(20) NOT NULL,
    total_users INTEGER DEFAULT 0,
    total_bookings INTEGER DEFAULT 0,
    total_revenue DECIMAL(10, 2) DEFAULT 0,
    active_bookings INTEGER DEFAULT 0,
    completed_bookings INTEGER DEFAULT 0,
    pending_bookings INTEGER DEFAULT 0,
    new_customers INTEGER DEFAULT 0,
    avg_order_value DECIMAL(10, 2) DEFAULT 0,
    revenue_by_service JSONB,
    revenue_by_day JSONB,
    top_services JSONB,
    customer_growth JSONB,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create service_history view
CREATE OR REPLACE VIEW service_history AS
SELECT * FROM vehicle_care_history;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_total_bookings ON users(total_bookings DESC);
CREATE INDEX IF NOT EXISTS idx_services_total_revenue ON services(total_revenue DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_queue_position ON bookings(queue_position) WHERE queue_position IS NOT NULL;

-- Create helper functions for counters
CREATE OR REPLACE FUNCTION update_user_booking_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE users SET total_bookings = total_bookings + 1 WHERE id = NEW.user_id;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE users SET total_bookings = GREATEST(total_bookings - 1, 0) WHERE id = OLD.user_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_service_stats()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE services
        SET total_bookings = total_bookings + 1,
            total_revenue = total_revenue + COALESCE(NEW.total_price, 0)
        WHERE id = NEW.service_id;
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        IF (OLD.status != 'completed' AND NEW.status = 'completed') THEN
            UPDATE services SET total_revenue = total_revenue + COALESCE(NEW.total_price, 0) WHERE id = NEW.service_id;
        END IF;
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE services
        SET total_bookings = GREATEST(total_bookings - 1, 0),
            total_revenue = GREATEST(total_revenue - COALESCE(OLD.total_price, 0), 0)
        WHERE id = OLD.service_id;
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Create triggers
DROP TRIGGER IF EXISTS trigger_update_user_booking_count ON bookings;
CREATE TRIGGER trigger_update_user_booking_count
AFTER INSERT OR DELETE ON bookings
FOR EACH ROW EXECUTE FUNCTION update_user_booking_count();

DROP TRIGGER IF EXISTS trigger_update_service_stats ON bookings;
CREATE TRIGGER trigger_update_service_stats
AFTER INSERT OR UPDATE OR DELETE ON bookings
FOR EACH ROW EXECUTE FUNCTION update_service_stats();

-- =============================================================================
-- PART 2: ROW LEVEL SECURITY (from migration 007)
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll ENABLE ROW LEVEL SECURITY;
ALTER TABLE fleet_vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE smart_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_care_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_snapshots ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN (SELECT schemaname, tablename, policyname FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', r.policyname, r.schemaname, r.tablename);
    END LOOP;
END $$;

-- Create helper functions
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION is_staff()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('staff', 'admin'));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create policies for USERS table
CREATE POLICY "users_insert_own" ON users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "users_select_own" ON users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "users_update_own" ON users FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "users_select_admin" ON users FOR SELECT USING (is_admin());
CREATE POLICY "users_update_admin" ON users FOR UPDATE USING (is_admin());
CREATE POLICY "users_delete_admin" ON users FOR DELETE USING (is_admin());
CREATE POLICY "users_select_staff" ON users FOR SELECT USING (is_staff() AND role = 'customer');

-- Create policies for VEHICLES table
CREATE POLICY "vehicles_select_own" ON vehicles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "vehicles_insert_own" ON vehicles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "vehicles_update_own" ON vehicles FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "vehicles_delete_own" ON vehicles FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "vehicles_select_staff" ON vehicles FOR SELECT USING (is_staff());
CREATE POLICY "vehicles_all_admin" ON vehicles FOR ALL USING (is_admin());

-- Create policies for SERVICES table
CREATE POLICY "services_select_public" ON services FOR SELECT USING (is_active = true);
CREATE POLICY "services_select_staff" ON services FOR SELECT USING (is_staff());
CREATE POLICY "services_insert_admin" ON services FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "services_update_admin" ON services FOR UPDATE USING (is_admin());
CREATE POLICY "services_delete_admin" ON services FOR DELETE USING (is_admin());

-- Create policies for BOOKINGS table
CREATE POLICY "bookings_select_own" ON bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "bookings_insert_own" ON bookings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "bookings_update_own" ON bookings FOR UPDATE USING (auth.uid() = user_id AND status IN ('pending', 'confirmed'));
CREATE POLICY "bookings_select_staff" ON bookings FOR SELECT USING (is_staff());
CREATE POLICY "bookings_update_staff" ON bookings FOR UPDATE USING (is_staff());
CREATE POLICY "bookings_all_admin" ON bookings FOR ALL USING (is_admin());

-- Create policies for REVIEWS table
CREATE POLICY "reviews_select_public" ON reviews FOR SELECT USING (is_public = true);
CREATE POLICY "reviews_select_own" ON reviews FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "reviews_insert_own" ON reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "reviews_update_own" ON reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "reviews_delete_own" ON reviews FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "reviews_all_admin" ON reviews FOR ALL USING (is_admin());

-- Create policies for NOTIFICATIONS table
CREATE POLICY "notifications_select_own" ON notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "notifications_update_own" ON notifications FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "notifications_insert_system" ON notifications FOR INSERT WITH CHECK (true);

-- Create policies for other tables (admin/staff only)
CREATE POLICY "employees_all_admin" ON employees FOR ALL USING (is_admin());
CREATE POLICY "payroll_all_admin" ON payroll FOR ALL USING (is_admin());
CREATE POLICY "fleet_vehicles_all_admin" ON fleet_vehicles FOR ALL USING (is_admin());
CREATE POLICY "inventory_items_all_admin" ON inventory_items FOR ALL USING (is_admin());
CREATE POLICY "inventory_transactions_all_admin" ON inventory_transactions FOR ALL USING (is_admin());
CREATE POLICY "analytics_snapshots_select_staff" ON analytics_snapshots FOR SELECT USING (is_staff());
CREATE POLICY "analytics_snapshots_all_admin" ON analytics_snapshots FOR ALL USING (is_admin());

-- Smart schedules (public can view)
CREATE POLICY "smart_schedules_select_all" ON smart_schedules FOR SELECT USING (true);
CREATE POLICY "smart_schedules_all_admin" ON smart_schedules FOR ALL USING (is_admin());

-- Customer engagement tables
CREATE POLICY "loyalty_programs_own" ON loyalty_programs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "subscriptions_own" ON subscriptions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "wallets_own" ON wallets FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "vehicle_care_history_own" ON vehicle_care_history FOR SELECT USING (
    EXISTS (SELECT 1 FROM vehicles WHERE vehicles.id = vehicle_care_history.vehicle_id AND vehicles.user_id = auth.uid())
);
CREATE POLICY "vehicle_care_history_staff" ON vehicle_care_history FOR ALL USING (is_staff());

-- Financial transactions
CREATE POLICY "financial_transactions_own" ON financial_transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "financial_transactions_staff" ON financial_transactions FOR SELECT USING (is_staff());
CREATE POLICY "financial_transactions_admin" ON financial_transactions FOR ALL USING (is_admin());

-- Attendance
CREATE POLICY "attendance_own" ON attendance FOR SELECT USING (
    EXISTS (SELECT 1 FROM employees WHERE employees.id = attendance.employee_id AND employees.user_id = auth.uid())
);
CREATE POLICY "attendance_staff" ON attendance FOR SELECT USING (is_staff());
CREATE POLICY "attendance_admin" ON attendance FOR ALL USING (is_admin());

-- Grant permissions
GRANT EXECUTE ON FUNCTION is_admin() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION is_staff() TO authenticated, anon;

-- =============================================================================
-- PART 3: UPDATE SCHEMA VERSION
-- =============================================================================

INSERT INTO schema_version (version, description)
VALUES ('2.4.0', 'Combined migration: Schema updates (counters, notifications, indexes) + Row Level Security (36 tables, 90+ policies)')
ON CONFLICT (version) DO NOTHING;

-- =============================================================================
-- VERIFICATION & SUMMARY
-- =============================================================================

DO $$
DECLARE
    total_tables INTEGER;
    tables_with_rls INTEGER;
    total_policies INTEGER;
    notifications_exists BOOLEAN;
    analytics_exists BOOLEAN;
BEGIN
    -- Count tables with RLS
    SELECT COUNT(*) INTO total_tables FROM pg_tables WHERE schemaname = 'public';

    SELECT COUNT(*) INTO tables_with_rls
    FROM pg_tables t
    WHERE schemaname = 'public'
    AND EXISTS (SELECT 1 FROM pg_class c WHERE c.relname = t.tablename AND c.relrowsecurity = true);

    SELECT COUNT(*) INTO total_policies FROM pg_policies WHERE schemaname = 'public';

    SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'notifications') INTO notifications_exists;
    SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'analytics_snapshots') INTO analytics_exists;

    RAISE NOTICE '=============================================================================';
    RAISE NOTICE 'Combined Migration Complete!';
    RAISE NOTICE '=============================================================================';
    RAISE NOTICE 'Schema Updates:';
    RAISE NOTICE '  ✓ Users.total_bookings counter added';
    RAISE NOTICE '  ✓ Services.total_bookings & total_revenue counters added';
    RAISE NOTICE '  ✓ Bookings.queue_position field added';
    RAISE NOTICE '  ✓ Notifications table: %', CASE WHEN notifications_exists THEN 'Created' ELSE 'Already exists' END;
    RAISE NOTICE '  ✓ Analytics_snapshots table: %', CASE WHEN analytics_exists THEN 'Created' ELSE 'Already exists' END;
    RAISE NOTICE '  ✓ Auto-update triggers installed';
    RAISE NOTICE '  ✓ Performance indexes created';
    RAISE NOTICE '';
    RAISE NOTICE 'Row Level Security:';
    RAISE NOTICE '  ✓ Total tables: %', total_tables;
    RAISE NOTICE '  ✓ Tables with RLS enabled: %', tables_with_rls;
    RAISE NOTICE '  ✓ Security policies created: %', total_policies;
    RAISE NOTICE '  ✓ Helper functions: is_admin(), is_staff()';
    RAISE NOTICE '';
    RAISE NOTICE 'Schema version updated to 2.4.0';
    RAISE NOTICE '=============================================================================';
END $$;
